version: '3'
services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app

  #It does not work (Better to run test on the same 
  #container as development in a seperate cmd window)
  tests:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: ["npm","run","test"]

  production:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      